apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassignment-api-deployment
  namespace: orchestration-homeassignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homeassignment-api
  template:
    metadata:
      labels:
        app: homeassignment-api
    spec:
      containers:
      - name: homeassignment-api
        image: homeassignment-registry/homeassignment:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: homeassignment-api-service
  namespace: orchestration-homeassignment
spec:
  selector:
    app: homeassignment-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP